services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ats_db
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
 
volumes:
  pgdata:
