# Generated by Django 5.2.1 on 2025-06-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0003_alter_candidate_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="phone_number",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
